repo: adopt `rust-lang` label system
Cuprate/cuprate pull request #136
Opened 2024-05-24 01:19 UTC by hinto-janai

2024-05-25 00:12 UTC, Boog900 requested changes
To add labels do you just add them to `labeler.yml`, whats the process?

2024-05-25 00:12 UTC, Boog900 commented on .github/labeler.yml
> +- net/*
Is this supposed to be duplicated?

2024-05-26 20:48 UTC, hinto-janai commented on .github/labeler.yml
> +- net/*
Nope, fixed

2024-05-26 21:08 UTC, hinto-janai commented
> To add labels do you just add them to labeler.yml, whats the process?

I added some docs to `.github/labeler.yml`.

Basically you define patterns that when [labeler](https://github.com/actions/labeler) matches in CI, it will automatically add/remove labels from a PR.

Examples here: https://github.com/hinto-janai/labeler-test/pulls

2024-05-26 23:56 UTC, Boog900 approved these changes
Looks good!

2024-05-26 23:57 UTC, merged