books: add skeleton and docs
Cuprate/cuprate pull request #141
Opened 2024-05-29 20:44 UTC by hinto-janai

- Adds `README.md` files for `books/`
- Adds `books/` related info in `CONTRIBUTING.md`
- Adds book build files to `.gitignore`

2024-05-29 20:45 UTC, hinto-janai commented
@Boog900
- Should I move `monero-book`'s source here, now?
- I'll going to keep `architecture-book` in a separate repo for now since things will change fast and there's stuff to figure out
- Can you add a DNS entry for `architecture.cuprate.org` pointing to https://github.com/Cuprate/architecture-book?

2024-05-29 21:53 UTC, Boog900 commented
> Should I move monero-book's source here, now?

I'll do this in a separate PR 

> Can you add a DNS entry for architecture.cuprate.org pointing to https://github.com/Cuprate/architecture-book?

done, I think you will have to deploy something there to see if it worked

2024-05-30 00:13 UTC, Boog900 requested changes

2024-05-30 00:13 UTC, Boog900 commented on CONTRIBUTING.md
> +Please contribute if you found a mistake! The files are mostly [markdown](https://wikipedia.org/wiki/Markdown) files and can be easily edited. See the `books/` directory for more information.
```suggestion
Please contribute if you find a mistake! The files are mostly [markdown](https://wikipedia.org/wiki/Markdown) files and can be easily edited. See the `books/` directory for more information.
```

2024-05-30 00:19 UTC, Boog900 commented on CONTRIBUTING.md
> +Please contribute if you found a mistake! The files are mostly [markdown](https://wikipedia.org/wiki/Markdown) files and can be easily edited. See the `books/` directory for more information.
wait I think both ok, my bad

2024-05-30 00:19 UTC, Boog900 approved these changes

2024-05-30 00:19 UTC, merged