books: add `user-book` skeleton
Cuprate/cuprate pull request #165
Opened 2024-06-16 18:46 UTC by hinto-janai

2025-03-10 21:22 UTC, hinto-janai commented on books/user/src/platform.md
> +| Manual testing      | 🟢     | 🟡 (sometimes)    | 🔴
Basic platform support rules for `v0.0.1`.

`Tier 1` are ones I can currently test; I don't have a reliable Windows machine setup yet so `Tier 2` for now. Official builds for `v0.0.1` will be:

- `x64 Linux`
- `ARM64 Linux`
- `x64 macOS`
- `ARM64 macOS`
- `x64 Windows`

2025-03-10 21:22 UTC, hinto-janai commented on books/user/src/getting-started/download.md
> +All release files are archived and also available at <https://archive.cuprate.org>.
@Boog900 Many projects have controlled archive/download servers, I think we should too.

DNS: `archive.cuprate.org` -> `5.104.84.64`. The file structure will be:
```
./
└── cuprated/
    ├── 0.0.1/
    │   ├── cuprated-0.0.1-linux-x64.tar.gz
    │   ├── cuprated-0.0.1-macos-arm64.tar.gz
    │   ├── [...]
    │   ├── SHA256SUMS
    │   └── SHA256SUMS.asc
    └── 0.0.2/
        └── [ ... same thing ... ]
```

2025-03-10 22:16 UTC, SyntheticBird45 requested changes

2025-03-10 22:16 UTC, SyntheticBird45 commented on books/user/src/getting-started/sys-req.md
> +| Disk (space)         | 400+ GB           | 250 GB
On my machine the database is 260GB. Might be good to increment it to 300GB

2025-03-10 22:16 UTC, SyntheticBird45 commented on books/user/src/introduction.md
> +In real terms, 20 hour full verification syncs and 4 hour fast-sync syncs have been reported on consumer grade hardware. Various testing results can be found [here](https://github.com/Cuprate/cuprate
We have achieved sub 2 hour (1h50m) fast-sync with 14 threads and 10Gbps. Might be good to make a note about bandwidth bottleneck

2025-03-11 21:47 UTC, SyntheticBird45 approved these changes

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/getting-started/sys-req.md
> +- Can run on weaker hardware (last tested on a `Raspberry Pi 4 (2GB RAM)` and `Raspberry Pi 5 (8 GB RAM)`)
```suggestion
- Can run on weaker hardware (last tested on a `Raspberry Pi 4 (2GB RAM)` and `Raspberry Pi 5 (8 GB RAM)`)
- Requires tweaking the config for your system, especially if your are at either extremes of the hardware scale.
```

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/introduction.md
> +The current full verification sync timings are around 1.4x~3x faster than `monerod`.
```suggestion
The current full verification sync timings are around 7.5x faster than `monerod`.
```

I think the 1.4 was done before the DB improvements and the 3x was done just after them, right? I got the 7.5x last week

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/introduction.md
> +In real terms, 20 hour full verification syncs and 4 hour fast-sync syncs have been reported on consumer grade hardware. On faster hardware (14 threads, 10Gbps networking), sub 2 hour fast-syncs have
```suggestion
In real terms, 16 hour full verification syncs and 4 hour fast-sync syncs have been reported on consumer grade hardware. On faster hardware (14 threads, 10Gbps networking), sub 2 hour fast-syncs have been reported.
```

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/introduction.md
> +`cuprated` does not currently emit a message indicating it is finished syncing, although it does log its block height status when syncing, for example:
We do emit `synchronised with the network` when synced, although it was buggy before #389, it _should_ be more stable now.

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/introduction.md
> +`cuprated` does not currently emit a message indicating it is finished syncing, although it does log its block height status when syncing, for example:
still a good idea to include how to read the logs just in case + maybe tell people to use `status`

2025-03-11 21:57 UTC, Boog900 commented on books/user/src/resources/disk.md
> +| `addressbook/ClearNet_p2p_state` | P2P state for clear-net
```suggestion
```
this was the old name which has been changed to just `ClearNet`

2025-03-11 22:19 UTC, Boog900 approved these changes

2025-03-11 22:19 UTC, merged

2025-03-11 23:24 UTC, Boog900 commented on books/user/src/getting-started/download.md
> +All release files are archived and also available at <https://archive.cuprate.org>.
Ah I forgot to comment here, IMO you should just use your own domain, rather than `cuprate`, I would support linking to that instead. 

We could potentially add more archives in the future.