database: return owned `T` in `Storable`
Cuprate/cuprate pull request #92
Opened 2024-03-18 00:12 UTC by hinto-janai

https://github.com/Cuprate/cuprate/pull/91 <- Previous

- `Storable::from_bytes(&[u8]) -> &T` -> `Storable::from_bytes(&[u8]) -> T`
- Adds `enum StorableSlice<'_, T>` for borrowed/owned slices
- Fixes `DatabaseRo::{get, get_range}()` to return `T` directly
- Removes `trait ValueGuard` as we return an owned `T` directly now

2024-03-20 20:30 UTC, hinto-janai commented
@Boog900 there's communication issues with Matrix.

Your reply after my:
```
both heed and redb will -> Cow<'_, T::Value> [...]
```
is encrypted, don't think you received some of my messages either. Email or post here maybe?

2024-03-20 20:42 UTC, Boog900 commented
Weird, I did use my laptop to message you when the first issue happend but since then I am back on my computer so it should be fine again.

Here was my message:



if we were to change the table definition in the table macro to `pub struct [<$table:camel>]<'a>(PhantomData<&'a ()>);`

Then on impl Table we can use this lifetime for the Value if needed.

I have made some VERY rough code just to test if this would work and it _seems_ to:

```rust
use core::marker::PhantomData;
use core::fmt::Debug;
use std::borrow::Cow;


trait Table {
    type T: Debug;
    
    fn new_t() -> Self::T;
}

struct TestTable<'a>(PhantomData<&'a ()>);

impl<'a> Table for TestTable<'a> {
    // Cow used in place of StorableSlice
    type T = Cow<'a, [u8]>;
    
    fn new_t() -> Cow<'static, [u8]> {
        Cow::Owned(vec![3, 2, 1])
    }
}

fn test_put<T: Table>(t: &T::T) {
    println!("{:?}", t)
}

fn test_get<T: Table>() -> T::T {
    T::new_t()
}

fn main() {
    let t = [1_u8,2,3];
    test_put::<TestTable>(&Cow::Borrowed(t.as_slice()));
    let tt = test_get::<TestTable>();
    println!("{:?}", tt)
}
```

2024-03-20 21:20 UTC, hinto-janai commented
It does seem to work but what about the special impl for `[u8]` and `Cow` as the returned type? It would allow us to just pass `[u8]` along, no alloc/cast.

Most types wouldn't have to copy inside `heed` either since we can return `Cow::Borrowed(casted_ref)`. The only type that would alloc is non `u8` slices. Are there more slice types than `[u8]` and `[u64]` we'll be using?

2024-03-20 21:31 UTC, Boog900 commented
\[u8\] has no alignment requirement https://doc.rust-lang.org/reference/type-layout.html#array-layout so I think whats happening is the [u8] is throwing off the key for that table which means the key will need to be special cased.

Plus this PR also allows us to remove the ValueGuard and Cow on return.

Even if we don't copy in `heed` we will end up copying data anyway as it gets returned from the service. 

> Are there more slice types than [u8] and [u64] we'll be using

No

2024-03-21 00:10 UTC, Boog900 commented
I tried to find a way to do this nicely with the current traits and I couldn't, I think what we are going to need to do is add a type like redb's [SelfType](https://docs.rs/redb/latest/redb/trait.RedbValue.html#associatedtype.SelfType) on our Storable trait and use this instead of self in the `as_bytes`/`from_bytes` method.

We would also need to change a lot of the signatures to now use <T::Value as Storable>::SelfType and <T::Key as Storable>::SelfType

2024-03-21 00:51 UTC, hinto-janai commented
Surely impl for `[u8]` and returning `Cow` is simpler at that point...?

2024-03-21 01:15 UTC, Boog900 commented
it's the u64, key, that needs the special impl 

I still think this PR is a good idea just to get rid of the 2 levels of indirection we have we returning values.

If we were to remove the StorableSlice completely and go with the plan of having a  `StorableVec` like:
```rust
struct StorableVec(Vec<T>)
```

and impl `RefCast` I think this would work .... in our messages you said that if we had a &[u8] we would have to collect into a Vec first but I can't think of a situation when adding data to the database through the service where you would only get a slice.

2024-03-21 19:59 UTC, hinto-janai commented
`StorableVec` would be a solution but any use-case that doesn't use `service` will suffer. I'm okay with doing this but just saying.

> so I think whats happening is the [u8] is throwing off the key for that table which means the key will need to be special cased

Btw I believe you are correct here - after testing no `bytemuck` on `[u8]` it still panics on the key.

2024-03-21 20:17 UTC, Boog900 commented
> any use-case that doesn't use service will suffer

I don't think these use cases will need to maximizes performance, so this should be ok

2024-03-21 21:43 UTC, hinto-janai reviewed
@Boog900 ready, added changes to the main post.

2024-03-21 21:43 UTC, hinto-janai commented on database/src/database.rs
> +    fn get(&self, key: &T::Key) -> Result<T::Value, RuntimeError>;
No more lifetimes needed, returned value is owned.

2024-03-21 21:43 UTC, hinto-janai commented on database/src/database.rs
> +    ) -> Result<impl Iterator<Item = Result<T::Value, RuntimeError>> + 'a, RuntimeError>
For `get_range()`, the iterator itself is tied to `self` and `range` but the values actually yielded from the iterator are fully owned, which is tested...

2024-03-21 21:43 UTC, hinto-janai commented on database/src/backend/tests.rs
> +    }
...here.

2024-03-22 13:36 UTC, Boog900 requested changes
I think the readme needs to be updated to remove references to value guard as well

2024-03-22 13:36 UTC, Boog900 commented on database/src/storable.rs
>      /// with no copying.
The docs here need to be updated as we are now copying

2024-03-22 13:36 UTC, Boog900 commented on database/src/tables.rs
>              impl Table for [<$table:camel>] {
is this allow needed?

2024-03-22 19:38 UTC, hinto-janai commented
Will we also need to add something like `Storable{Arc,Box,Bytes}<T>(pub {Arc,Box,Bytes}<T>)`?

2024-03-22 20:03 UTC, Boog900 commented
Yeah we will need a StorableBytes but I don't think we need any of the others

2024-03-22 20:07 UTC, Boog900 commented on database/src/storable.rs
>  pub trait Storable: ToOwnedDebug {
Do we still need `ToOwnedDebug`?

2024-03-22 20:42 UTC, hinto-janai commented
- Replaced `ToOwnedDebug` with regular `Debug`
- Added `StorableBytes(pub bytes::Bytes)`

2024-03-22 20:58 UTC, Boog900 approved these changes

2024-03-22 21:11 UTC, merged